export const ALL_DATA_REQUEST = "ALL_DATA_REQUEST";
export const ALL_DATA_SUCCESS = "ALL_DATA_SUCCESS";
export const ALL_DATA_FAIL = "ALL_DATA_FAIL";

export const ALL_CENTERS_REQUEST = "ALL_CENTERS_REQUEST";
export const ALL_CENTERS_SUCCESS = "ALL_CENTERS_SUCCESS";
export const ALL_CENTERS_FAIL = "ALL_CENTERS_FAIL";

export const ALL_ROOMS_REQUEST = "ALL_ROOMS_REQUEST";
export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";